version: "3"
services: 
  mysql000ex11:
    image: mysql:latest
    volumes:
      - mysql000vol11:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wordpress000db
      MYSQL_USER: wordpress000kun
      MYSQL_PASSWORD: wkunpass
    networks:
      - wordpress000net1

  wordpress000ex12:
    depends_on:
      - mysql000ex11
    image: wordpress
    networks:
      - wordpress000net1
    volumes:
      - wordpress000vol12:/var/www/html
    ports:
      - 8085:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql000ex11:3306  # 포트 추가
      WORDPRESS_DB_NAME: wordpress000db
      WORDPRESS_DB_USER: wordpress000kun
      WORDPRESS_DB_PASSWORD: wkunpass
    entrypoint: ["sh", "-c", "sleep 10; docker-entrypoint.sh apache2-foreground"]  # MySQL 초기화 대기

networks:
  wordpress000net1:

volumes:
  mysql000vol11:
  wordpress000vol12: